import type { MenuCategory } from "../../types/content";
import { contentSources } from "../shared/sources";

export const menuCategories: readonly MenuCategory[] = [
  {
    id: "cat-hot-dishes",
    slug: "platos-calientes",
    label: "Platos Calientes",
    description: null,
    order: 1,
    publicationStatus: "PUBLIC",
    sourceLabel: "Platos Calientes",
    sourceIds: [contentSources.siteMenu.id, contentSources.contentInventory.id],
  },
  {
    id: "cat-cold-dishes",
    slug: "platos-frios",
    label: "Platos Frios",
    description: null,
    order: 2,
    publicationStatus: "PUBLIC",
    sourceLabel: "Platos Fríos",
    sourceIds: [contentSources.siteMenu.id, contentSources.contentInventory.id],
  },
  {
    id: "cat-pizzas",
    slug: "pizzas",
    label: "Pizzas",
    description: null,
    order: 3,
    publicationStatus: "PUBLIC",
    sourceLabel: "Pizzas",
    sourceIds: [contentSources.siteMenu.id, contentSources.contentInventory.id],
  },
  {
    id: "cat-vermut",
    slug: "vermut",
    label: "Vermut",
    description: null,
    order: 4,
    publicationStatus: "PENDING_CONTENT",
    sourceLabel: "Vermut",
    note: "Category is visible in the audited menu, but no item-level content was recovered in Phase 0.",
    sourceIds: [contentSources.siteMenu.id, contentSources.contentInventory.id],
  },
  {
    id: "cat-sangrias",
    slug: "sangrias",
    label: "Sangrias",
    description: null,
    order: 5,
    publicationStatus: "PUBLIC",
    sourceLabel: "Sangrías",
    sourceIds: [contentSources.siteMenu.id, contentSources.contentInventory.id],
  },
  {
    id: "cat-cocktails",
    slug: "cocteles",
    label: "Cocteles",
    description: null,
    order: 6,
    publicationStatus: "PUBLIC",
    sourceLabel: "Cócteles",
    sourceIds: [contentSources.siteMenu.id, contentSources.contentInventory.id],
  },
  {
    id: "cat-beers",
    slug: "cervezas",
    label: "Cervezas",
    description: null,
    order: 7,
    publicationStatus: "PUBLIC",
    sourceLabel: "Cervezas",
    sourceIds: [contentSources.siteMenu.id, contentSources.contentInventory.id],
  },
  {
    id: "cat-soft-drinks",
    slug: "refrescos",
    label: "Refrescos",
    description: null,
    order: 8,
    publicationStatus: "PUBLIC",
    sourceLabel: "Refrescos",
    sourceIds: [contentSources.siteMenu.id, contentSources.contentInventory.id],
  },
  {
    id: "cat-wines",
    slug: "vinos",
    label: "Vinos",
    description: null,
    order: 9,
    publicationStatus: "PUBLIC",
    sourceLabel: "Vinos",
    sourceIds: [contentSources.siteMenu.id, contentSources.contentInventory.id],
  },
  {
    id: "cat-desserts",
    slug: "postres",
    label: "Postres",
    description: null,
    order: 10,
    publicationStatus: "PUBLIC",
    sourceLabel: "Postres",
    sourceIds: [contentSources.siteMenu.id, contentSources.contentInventory.id],
  },
];
