import type { MenuItem } from "../../types/content";
import { contentSources } from "../shared/sources";
import { getProposedPrice } from "./proposedPrices";

function pendingPrice(note?: string) {
  return {
    amount: null,
    currency: "EUR" as const,
    status: "PENDING_VALIDATION" as const,
    ...(note ? { note } : {}),
  };
}

function pendingMedia(assetId: string | null, alt: string | null) {
  return assetId
    ? {
        assetId,
        assetStatus: "VERIFIED" as const,
        crop: "original" as const,
        alt,
      }
    : null;
}

function menuItem(
  item: Omit<MenuItem, "references" | "ingredientStatus" | "allergenStatus">,
): MenuItem {
  return {
    ...item,
    ingredientStatus:
      item.publishedIngredients.length > 0 ? "VERIFIED" : "PENDING_CONTENT",
    allergenStatus: "PENDING_VALIDATION",
    references: {
      sourceIds: [
        contentSources.siteMenu.id,
        contentSources.contentInventory.id,
      ],
    },
  };
}

const sourcedMenuItems: readonly MenuItem[] = [
  menuItem({
    id: "item-gambas-ajillo",
    slug: "gambas-al-ajillo",
    sourceName: "Gambas al Ajillo",
    name: "Gambas al Ajillo",
    description: null,
    categoryId: "cat-hot-dishes",
    subcategory: null,
    publishedIngredients: [],
    price: pendingPrice("No public price was recovered from the audited site."),
    allergens: [],
    dietaryTags: [],
    spicyLevel: null,
    availability: "UNKNOWN",
    media: pendingMedia("asset-010", "Gambas al Ajillo de Malcriado"),
    editorialOrder: 1,
    publicationStatus: "PUBLIC",
  }),
  menuItem({
    id: "item-pulpo-chimichurri",
    slug: "pulpo-al-chimichurri",
    sourceName: "Pulpo al Chimichurri",
    name: "Pulpo al Chimichurri",
    description: null,
    categoryId: "cat-hot-dishes",
    subcategory: null,
    publishedIngredients: [],
    price: pendingPrice(),
    allergens: [],
    dietaryTags: [],
    spicyLevel: null,
    availability: "UNKNOWN",
    media: pendingMedia("asset-019", "Pulpo al Chimichurri de Malcriado"),
    editorialOrder: 2,
    publicationStatus: "PUBLIC",
  }),
  menuItem({
    id: "item-nachos-malcriados",
    slug: "nachos-malcriados",
    sourceName: "Nachos Malcriados",
    name: "Nachos Malcriados",
    description: null,
    categoryId: "cat-hot-dishes",
    subcategory: null,
    publishedIngredients: [],
    price: pendingPrice(),
    allergens: [],
    dietaryTags: ["SHAREABLE"],
    spicyLevel: null,
    availability: "UNKNOWN",
    media: pendingMedia("asset-017", "Nachos Malcriados"),
    editorialOrder: 3,
    publicationStatus: "PUBLIC",
  }),
  menuItem({
    id: "item-chicharrones-sinaloenses",
    slug: "chicharrones-sinaloenses",
    sourceName: "Chicharrones Sinaloenses",
    name: "Chicharrones Sinaloenses",
    description: null,
    categoryId: "cat-hot-dishes",
    subcategory: null,
    publishedIngredients: [],
    price: pendingPrice(),
    allergens: [],
    dietaryTags: [],
    spicyLevel: null,
    availability: "UNKNOWN",
    media: pendingMedia("asset-005", "Chicharrones Sinaloenses"),
    editorialOrder: 4,
    publicationStatus: "PUBLIC",
  }),
  menuItem({
    id: "item-tequenos-ud",
    slug: "tequenos-u-d",
    sourceName: "Tequeños U.D",
    name: "Tequeños U.D",
    description: null,
    categoryId: "cat-hot-dishes",
    subcategory: null,
    publishedIngredients: [],
    price: pendingPrice(
      "The suffix U.D is ambiguous and requires owner validation.",
    ),
    allergens: [],
    dietaryTags: [],
    spicyLevel: null,
    availability: "UNKNOWN",
    media: null,
    editorialOrder: 5,
    publicationStatus: "PENDING_VALIDATION",
    validationNotes:
      "The audited source preserves the original wording. Unit meaning still needs confirmation.",
  }),
  menuItem({
    id: "item-infladita-res",
    slug: "infladita-de-res",
    sourceName: "Infladita de Res",
    name: "Infladita de Res",
    description: null,
    categoryId: "cat-hot-dishes",
    subcategory: null,
    publishedIngredients: [],
    price: pendingPrice(),
    allergens: [],
    dietaryTags: [],
    spicyLevel: null,
    availability: "UNKNOWN",
    media: null,
    editorialOrder: 6,
    publicationStatus: "PENDING_VALIDATION",
  }),
  menuItem({
    id: "item-fajitas-mixta",
    slug: "fajitas-mixta",
    sourceName: "Fajitas Mixta",
    name: "Fajitas Mixta",
    description: null,
    categoryId: "cat-hot-dishes",
    subcategory: null,
    publishedIngredients: [],
    price: pendingPrice(),
    allergens: [],
    dietaryTags: [],
    spicyLevel: null,
    availability: "UNKNOWN",
    media: null,
    editorialOrder: 7,
    publicationStatus: "PENDING_VALIDATION",
    validationNotes:
      "Naming should be reviewed with the owner before normalization.",
  }),
  menuItem({
    id: "item-canelon-xxl",
    slug: "canelon-xxl",
    sourceName: "Canelón XXL",
    name: "Canelon XXL",
    description: null,
    categoryId: "cat-hot-dishes",
    subcategory: null,
    publishedIngredients: [],
    price: pendingPrice(),
    allergens: [],
    dietaryTags: [],
    spicyLevel: null,
    availability: "UNKNOWN",
    media: null,
    editorialOrder: 8,
    publicationStatus: "PENDING_VALIDATION",
  }),
  menuItem({
    id: "item-burrata",
    slug: "burrata",
    sourceName: "Burrata",
    name: "Burrata",
    description: null,
    categoryId: "cat-cold-dishes",
    subcategory: null,
    publishedIngredients: [],
    price: pendingPrice(),
    allergens: [],
    dietaryTags: ["VEGETARIAN"],
    spicyLevel: null,
    availability: "UNKNOWN",
    media: pendingMedia("asset-007", "Burrata de Malcriado"),
    editorialOrder: 1,
    publicationStatus: "PUBLIC",
  }),
  menuItem({
    id: "item-ceviche-tradicional",
    slug: "ceviche-tradicional",
    sourceName: "Ceviche Tradicional",
    name: "Ceviche Tradicional",
    description: null,
    categoryId: "cat-cold-dishes",
    subcategory: null,
    publishedIngredients: [],
    price: pendingPrice(),
    allergens: [],
    dietaryTags: [],
    spicyLevel: null,
    availability: "UNKNOWN",
    media: null,
    editorialOrder: 2,
    publicationStatus: "PUBLIC",
  }),
  menuItem({
    id: "item-tarta-atun",
    slug: "tarta-de-atun",
    sourceName: "Tarta de Atún",
    name: "Tarta de Atun",
    description: null,
    categoryId: "cat-cold-dishes",
    subcategory: null,
    publishedIngredients: [],
    price: pendingPrice(
      "Asset naming suggests tartar, but the recovered menu content says Tarta de Atún.",
    ),
    allergens: [],
    dietaryTags: [],
    spicyLevel: null,
    availability: "UNKNOWN",
    media: pendingMedia("asset-026", "Tarta de Atun de Malcriado"),
    editorialOrder: 3,
    publicationStatus: "PUBLIC",
    validationNotes:
      "Naming discrepancy between recovered copy and asset filename remains pending.",
  }),
  menuItem({
    id: "item-carpaccio-salmon-curado",
    slug: "carpaccio-de-salmon-curado",
    sourceName: "Carpaccio de Salmón Curado",
    name: "Carpaccio de Salmon Curado",
    description: null,
    categoryId: "cat-cold-dishes",
    subcategory: null,
    publishedIngredients: [],
    price: pendingPrice(),
    allergens: [],
    dietaryTags: [],
    spicyLevel: null,
    availability: "UNKNOWN",
    media: null,
    editorialOrder: 4,
    publicationStatus: "PUBLIC",
  }),
  menuItem({
    id: "item-ensalada-tomate-melocoton",
    slug: "ensalada-de-tomate-y-melocoton",
    sourceName: "Ensalada de Tomate y Melocotón",
    name: "Ensalada de Tomate y Melocoton",
    description: null,
    categoryId: "cat-cold-dishes",
    subcategory: null,
    publishedIngredients: [],
    price: pendingPrice(),
    allergens: [],
    dietaryTags: ["VEGETARIAN"],
    spicyLevel: null,
    availability: "SEASONAL",
    media: null,
    editorialOrder: 5,
    publicationStatus: "PUBLIC",
  }),
  menuItem({
    id: "item-pizza-calabrese-picante",
    slug: "calabrese-picante",
    sourceName: "Calabrese Picante",
    name: "Calabrese Picante",
    description: null,
    categoryId: "cat-pizzas",
    subcategory: null,
    publishedIngredients: [],
    price: pendingPrice(),
    allergens: [],
    dietaryTags: [],
    spicyLevel: 2,
    availability: "UNKNOWN",
    media: null,
    editorialOrder: 1,
    publicationStatus: "PUBLIC",
  }),
  menuItem({
    id: "item-pizza-prosciutto",
    slug: "prosciutto",
    sourceName: "Prosciutto",
    name: "Prosciutto",
    description: null,
    categoryId: "cat-pizzas",
    subcategory: null,
    publishedIngredients: [],
    price: pendingPrice(),
    allergens: [],
    dietaryTags: [],
    spicyLevel: null,
    availability: "UNKNOWN",
    media: null,
    editorialOrder: 2,
    publicationStatus: "PUBLIC",
  }),
  menuItem({
    id: "item-pizza-hawaiana",
    slug: "hawaiana",
    sourceName: "Hawaiana",
    name: "Hawaiana",
    description: null,
    categoryId: "cat-pizzas",
    subcategory: null,
    publishedIngredients: [],
    price: pendingPrice(),
    allergens: [],
    dietaryTags: [],
    spicyLevel: null,
    availability: "UNKNOWN",
    media: null,
    editorialOrder: 3,
    publicationStatus: "PUBLIC",
  }),
  menuItem({
    id: "item-pizza-malcriada",
    slug: "la-malcriada",
    sourceName: "La Malcriada",
    name: "La Malcriada",
    description: null,
    categoryId: "cat-pizzas",
    subcategory: null,
    publishedIngredients: [],
    price: pendingPrice(),
    allergens: [],
    dietaryTags: [],
    spicyLevel: null,
    availability: "UNKNOWN",
    media: pendingMedia("asset-018", "Pizza de Malcriado"),
    editorialOrder: 4,
    publicationStatus: "PUBLIC",
  }),
  menuItem({
    id: "item-pizza-margarita",
    slug: "pizza-margarita",
    sourceName: "Margarita",
    name: "Margarita",
    description: null,
    categoryId: "cat-pizzas",
    subcategory: null,
    publishedIngredients: [],
    price: pendingPrice(),
    allergens: [],
    dietaryTags: ["VEGETARIAN"],
    spicyLevel: null,
    availability: "UNKNOWN",
    media: null,
    editorialOrder: 5,
    publicationStatus: "PUBLIC",
  }),
  menuItem({
    id: "item-sangria",
    slug: "sangria",
    sourceName: "Sangría",
    name: "Sangria",
    description: null,
    categoryId: "cat-sangrias",
    subcategory: null,
    publishedIngredients: [],
    price: pendingPrice(),
    allergens: [],
    dietaryTags: [],
    spicyLevel: null,
    availability: "UNKNOWN",
    media: null,
    editorialOrder: 1,
    publicationStatus: "PUBLIC",
  }),
  menuItem({
    id: "item-tinto-verano",
    slug: "tinto-verano",
    sourceName: "Tinto Verano",
    name: "Tinto Verano",
    description: null,
    categoryId: "cat-sangrias",
    subcategory: null,
    publishedIngredients: [],
    price: pendingPrice(),
    allergens: [],
    dietaryTags: [],
    spicyLevel: null,
    availability: "UNKNOWN",
    media: null,
    editorialOrder: 2,
    publicationStatus: "PUBLIC",
  }),
  menuItem({
    id: "item-sangria-litro",
    slug: "sangria-litro",
    sourceName: "Sangría Litro",
    name: "Sangria Litro",
    description: null,
    categoryId: "cat-sangrias",
    subcategory: null,
    publishedIngredients: [],
    price: pendingPrice(),
    allergens: [],
    dietaryTags: ["SHAREABLE"],
    spicyLevel: null,
    availability: "UNKNOWN",
    media: null,
    editorialOrder: 3,
    publicationStatus: "PUBLIC",
  }),
  menuItem({
    id: "item-sangria-cava",
    slug: "sangria-cava",
    sourceName: "Sangría Cava",
    name: "Sangria Cava",
    description: null,
    categoryId: "cat-sangrias",
    subcategory: null,
    publishedIngredients: [],
    price: pendingPrice(),
    allergens: [],
    dietaryTags: [],
    spicyLevel: null,
    availability: "UNKNOWN",
    media: null,
    editorialOrder: 4,
    publicationStatus: "PUBLIC",
  }),
  menuItem({
    id: "item-mojito-clasico",
    slug: "mojito-clasico",
    sourceName: "Mojito Clásico",
    name: "Mojito Clasico",
    description: null,
    categoryId: "cat-cocktails",
    subcategory: "Mojitos",
    publishedIngredients: [],
    price: pendingPrice(),
    allergens: [],
    dietaryTags: [],
    spicyLevel: null,
    availability: "UNKNOWN",
    media: pendingMedia("asset-015", "Mojito clasico"),
    editorialOrder: 1,
    publicationStatus: "PUBLIC",
  }),
  menuItem({
    id: "item-mojito-sin-alcohol",
    slug: "mojito-sin-alcohol",
    sourceName: "Mojito sin Alcohol",
    name: "Mojito sin Alcohol",
    description: null,
    categoryId: "cat-cocktails",
    subcategory: "Mojitos",
    publishedIngredients: [],
    price: pendingPrice(),
    allergens: [],
    dietaryTags: ["NON_ALCOHOLIC"],
    spicyLevel: null,
    availability: "UNKNOWN",
    media: null,
    editorialOrder: 2,
    publicationStatus: "PUBLIC",
  }),
  menuItem({
    id: "item-margarita",
    slug: "margarita",
    sourceName: "Margarita",
    name: "Margarita",
    description: null,
    categoryId: "cat-cocktails",
    subcategory: "Margaritas",
    publishedIngredients: [],
    price: pendingPrice(),
    allergens: [],
    dietaryTags: [],
    spicyLevel: null,
    availability: "UNKNOWN",
    media: pendingMedia("asset-013", "Margarita de fresa"),
    editorialOrder: 3,
    publicationStatus: "PENDING_VALIDATION",
    validationNotes:
      "The audited menu mixes Margarita with flavor-only entries Maracuyá and Fresa.",
  }),
  menuItem({
    id: "item-margarita-maracuya",
    slug: "margarita-maracuya",
    sourceName: "Maracuyá",
    name: "Maracuya",
    description:
      "Entrada visible en la categoria de cocteles; requiere confirmacion de si es variante de Margarita u oferta independiente.",
    categoryId: "cat-cocktails",
    subcategory: "Margaritas",
    publishedIngredients: [],
    price: pendingPrice(),
    allergens: [],
    dietaryTags: [],
    spicyLevel: null,
    availability: "UNKNOWN",
    media: null,
    editorialOrder: 4,
    publicationStatus: "PENDING_VALIDATION",
  }),
  menuItem({
    id: "item-margarita-fresa",
    slug: "margarita-fresa",
    sourceName: "Fresa",
    name: "Fresa",
    description:
      "Entrada visible en la categoria de cocteles; requiere confirmacion de si es variante de Margarita u oferta independiente.",
    categoryId: "cat-cocktails",
    subcategory: "Margaritas",
    publishedIngredients: [],
    price: pendingPrice(),
    allergens: [],
    dietaryTags: [],
    spicyLevel: null,
    availability: "UNKNOWN",
    media: pendingMedia("asset-012", "Margarita de fresa coctel"),
    editorialOrder: 5,
    publicationStatus: "PENDING_VALIDATION",
  }),
  menuItem({
    id: "item-alhambra",
    slug: "alhambra",
    sourceName: "Alhambra",
    name: "Alhambra",
    description: null,
    categoryId: "cat-beers",
    subcategory: null,
    publishedIngredients: [],
    price: pendingPrice(),
    allergens: [],
    dietaryTags: [],
    spicyLevel: null,
    availability: "UNKNOWN",
    media: null,
    editorialOrder: 1,
    publicationStatus: "PUBLIC",
  }),
  menuItem({
    id: "item-mahou",
    slug: "mahou",
    sourceName: "Mahou",
    name: "Mahou",
    description: null,
    categoryId: "cat-beers",
    subcategory: null,
    publishedIngredients: [],
    price: pendingPrice(),
    allergens: [],
    dietaryTags: [],
    spicyLevel: null,
    availability: "UNKNOWN",
    media: null,
    editorialOrder: 2,
    publicationStatus: "PUBLIC",
  }),
  menuItem({
    id: "item-corona",
    slug: "corona",
    sourceName: "Corona",
    name: "Corona",
    description: null,
    categoryId: "cat-beers",
    subcategory: null,
    publishedIngredients: [],
    price: pendingPrice(),
    allergens: [],
    dietaryTags: [],
    spicyLevel: null,
    availability: "UNKNOWN",
    media: pendingMedia("asset-006", "Cubo de Coronitas"),
    editorialOrder: 3,
    publicationStatus: "PUBLIC",
  }),
  menuItem({
    id: "item-coca-cola",
    slug: "coca-cola",
    sourceName: "Coca Cola",
    name: "Coca Cola",
    description: null,
    categoryId: "cat-soft-drinks",
    subcategory: null,
    publishedIngredients: [],
    price: pendingPrice(),
    allergens: [],
    dietaryTags: ["NON_ALCOHOLIC"],
    spicyLevel: null,
    availability: "UNKNOWN",
    media: null,
    editorialOrder: 1,
    publicationStatus: "PUBLIC",
  }),
  menuItem({
    id: "item-fanta",
    slug: "fanta",
    sourceName: "Fanta",
    name: "Fanta",
    description: null,
    categoryId: "cat-soft-drinks",
    subcategory: null,
    publishedIngredients: [],
    price: pendingPrice(),
    allergens: [],
    dietaryTags: ["NON_ALCOHOLIC"],
    spicyLevel: null,
    availability: "UNKNOWN",
    media: null,
    editorialOrder: 2,
    publicationStatus: "PUBLIC",
  }),
  menuItem({
    id: "item-nestea",
    slug: "nestea",
    sourceName: "Nestea",
    name: "Nestea",
    description: null,
    categoryId: "cat-soft-drinks",
    subcategory: null,
    publishedIngredients: [],
    price: pendingPrice(),
    allergens: [],
    dietaryTags: ["NON_ALCOHOLIC"],
    spicyLevel: null,
    availability: "UNKNOWN",
    media: null,
    editorialOrder: 3,
    publicationStatus: "PUBLIC",
  }),
  menuItem({
    id: "item-red-bull",
    slug: "red-bull",
    sourceName: "Red Bull",
    name: "Red Bull",
    description: null,
    categoryId: "cat-soft-drinks",
    subcategory: null,
    publishedIngredients: [],
    price: pendingPrice(),
    allergens: [],
    dietaryTags: ["NON_ALCOHOLIC"],
    spicyLevel: null,
    availability: "UNKNOWN",
    media: null,
    editorialOrder: 4,
    publicationStatus: "PUBLIC",
  }),
  menuItem({
    id: "item-tonica",
    slug: "tonica",
    sourceName: "Tónica",
    name: "Tonica",
    description: null,
    categoryId: "cat-soft-drinks",
    subcategory: null,
    publishedIngredients: [],
    price: pendingPrice(),
    allergens: [],
    dietaryTags: ["NON_ALCOHOLIC"],
    spicyLevel: null,
    availability: "UNKNOWN",
    media: null,
    editorialOrder: 5,
    publicationStatus: "PUBLIC",
  }),
  menuItem({
    id: "item-bitter-kas",
    slug: "bitter-kas",
    sourceName: "Bitter Kas",
    name: "Bitter Kas",
    description: null,
    categoryId: "cat-soft-drinks",
    subcategory: null,
    publishedIngredients: [],
    price: pendingPrice(),
    allergens: [],
    dietaryTags: ["NON_ALCOHOLIC"],
    spicyLevel: null,
    availability: "UNKNOWN",
    media: null,
    editorialOrder: 6,
    publicationStatus: "PUBLIC",
  }),
  menuItem({
    id: "item-vino-tinto",
    slug: "vino-tinto",
    sourceName: "Tinto",
    name: "Vino Tinto",
    description:
      "Entrada generica recuperada desde la categoria de vinos. Formato visible: copa y botella.",
    categoryId: "cat-wines",
    subcategory: "Copa y botella",
    publishedIngredients: [],
    price: pendingPrice(),
    allergens: [],
    dietaryTags: [],
    spicyLevel: null,
    availability: "UNKNOWN",
    media: null,
    editorialOrder: 1,
    publicationStatus: "PENDING_VALIDATION",
  }),
  menuItem({
    id: "item-vino-blanco",
    slug: "vino-blanco",
    sourceName: "Blanco",
    name: "Vino Blanco",
    description:
      "Entrada generica recuperada desde la categoria de vinos. Formato visible: copa y botella.",
    categoryId: "cat-wines",
    subcategory: "Copa y botella",
    publishedIngredients: [],
    price: pendingPrice(),
    allergens: [],
    dietaryTags: [],
    spicyLevel: null,
    availability: "UNKNOWN",
    media: null,
    editorialOrder: 2,
    publicationStatus: "PENDING_VALIDATION",
  }),
  menuItem({
    id: "item-vino-rosado",
    slug: "vino-rosado",
    sourceName: "Rosado",
    name: "Vino Rosado",
    description:
      "Entrada generica recuperada desde la categoria de vinos. Formato visible: copa y botella.",
    categoryId: "cat-wines",
    subcategory: "Copa y botella",
    publishedIngredients: [],
    price: pendingPrice(),
    allergens: [],
    dietaryTags: [],
    spicyLevel: null,
    availability: "UNKNOWN",
    media: null,
    editorialOrder: 3,
    publicationStatus: "PENDING_VALIDATION",
  }),
  menuItem({
    id: "item-cava",
    slug: "cava",
    sourceName: "Cava",
    name: "Cava",
    description:
      "Entrada generica recuperada desde la categoria de vinos. Formato visible: copa y botella.",
    categoryId: "cat-wines",
    subcategory: "Copa y botella",
    publishedIngredients: [],
    price: pendingPrice(),
    allergens: [],
    dietaryTags: [],
    spicyLevel: null,
    availability: "UNKNOWN",
    media: null,
    editorialOrder: 4,
    publicationStatus: "PENDING_VALIDATION",
  }),
  menuItem({
    id: "item-merengon-fresa",
    slug: "merengon-de-fresa",
    sourceName: "Merengón de Fresa",
    name: "Merengon de Fresa",
    description: null,
    categoryId: "cat-desserts",
    subcategory: null,
    publishedIngredients: [],
    price: pendingPrice(),
    allergens: [],
    dietaryTags: [],
    spicyLevel: null,
    availability: "UNKNOWN",
    media: null,
    editorialOrder: 1,
    publicationStatus: "PUBLIC",
  }),
  menuItem({
    id: "item-tarta-tres-leches",
    slug: "tarta-tres-leches",
    sourceName: "Tarta tres Leches",
    name: "Tarta tres Leches",
    description: null,
    categoryId: "cat-desserts",
    subcategory: null,
    publishedIngredients: [],
    price: pendingPrice(),
    allergens: [],
    dietaryTags: [],
    spicyLevel: null,
    availability: "UNKNOWN",
    media: null,
    editorialOrder: 2,
    publicationStatus: "PUBLIC",
  }),
  menuItem({
    id: "item-tarta-queso",
    slug: "tarta-de-queso",
    sourceName: "Tarta de Queso",
    name: "Tarta de Queso",
    description: null,
    categoryId: "cat-desserts",
    subcategory: null,
    publishedIngredients: [],
    price: pendingPrice(),
    allergens: [],
    dietaryTags: ["VEGETARIAN"],
    spicyLevel: null,
    availability: "UNKNOWN",
    media: null,
    editorialOrder: 3,
    publicationStatus: "PUBLIC",
  }),
  menuItem({
    id: "item-coulant-chocolate",
    slug: "coulant-de-chocolate",
    sourceName: "Coulant de Chocolate",
    name: "Coulant de Chocolate",
    description: null,
    categoryId: "cat-desserts",
    subcategory: null,
    publishedIngredients: [],
    price: pendingPrice(),
    allergens: [],
    dietaryTags: ["VEGETARIAN"],
    spicyLevel: null,
    availability: "UNKNOWN",
    media: null,
    editorialOrder: 4,
    publicationStatus: "PUBLIC",
  }),
];

export const menuItems: readonly MenuItem[] = sourcedMenuItems.map((item) => ({
  ...item,
  price:
    item.price.amount !== null
      ? item.price
      : getProposedPrice(item.categoryId, item.editorialOrder),
}));
